run_every = "5m"

ignore_meshviewer = "6h"
ignore_node = "3d"

status_json = "/var/www/html/collector/status.json"

##
# dataPaths

[dataPaths]
## 3 Laendereck (invlaid format - non-standard)
# "https://map.freifunk-3laendereck.net/data/meshviewer.json" = "3laendereck"

## Altdorf
"https://map.tecff.de/yanic/meshviewer.json" = "altdorf"

## Aachen + regio aachen
"https://data.aachen.freifunk.net/meshviewer.json" = "aachen"

## Bielefeld (invlaid format - non-standard)
# "https://map.freifunk-bielefeld.de/meshviewer/data/meshviewer.json" = "bielefeld"

## Bodensee (invlaid format - non-standard)
# "https://mate.ffbsee.net/data/meshviewer.json" = "bodensee"

## Bremen
"https://downloads.bremen.freifunk.net/data/meshviewer.json" = "bremen"

## Darmstadt
"https://meshviewer.darmstadt.freifunk.net/data/meshviewer.json" = "darmstadt"

## Dresden
"https://meshviewer.freifunk-dresden.de/data/meshviewer.json" = "dresden"

## Duesseldorf
"https://map.freifunk-duesseldorf.de/data/meshviewer.json" = "duesseldorf"

## Einbeck
"http://vps643489.ovh.net/meshviewer/data/meshviewer.json" = "einbeck"

## Erfurt
"https://map.erfurt.freifunk.net/meshviewer/data/meshviewer.json" = "erfurt"

## Essen
"https://map.freifunk-essen.de/data/meshviewer.json" = "essen"

## Ennepe-Ruhr-Kreis
"https://karte.ff-en.de/data/meshviewer.json" = "en-kreis"

## Eulenfunk (no active ffeds)
#"https://freudenberg.map.eulenfunk.de/new/data/meshviewer.json" = "freudenberg"
#"https://gek.map.eulenfunk.de/new/data/meshviewer.json" = "gelsenkirchen"
#"https://hilchenbach.map.eulenfunk.de/new/data/meshviewer.json" = "hilchenbach"
#"https://mk.map.eulenfunk.de/new/data/meshviewer.json" = "maerkischer-kreis"
#"https://rade.map.eulenfunk.de/new/data/meshviewer.json" = "radevormwald"
#"https://siegen.map.eulenfunk.de/new/data/meshviewer.json" = "siegen"
#"https://wup.map.eulenfunk.de/new/data/meshviewer.json" = "wuppertal"

## Flingern (no active feed)
#"https://karte.ffdus.de/new/data/meshviewer.json" = "flingern"

## Frankfurt
"https://yanic.batman15.ffffm.net/meshviewer.json" = "frankfurt"

## Fulda
"https://meshviewer.fulda.freifunk.net/data/meshviewer.json" = "fulda"

## Gera-Greiz
"https://www.freifunk-gera-greiz.de/meshviewer/data/meshviewer.json" = "gera-greiz"

## Gladbach (no active feeds)
#"https://bgl.map.ffgl.eu/new/data/meshviewer.json" = "bergisch-gladbach"
#"https://bcd.map.ffgl.eu/new/data/meshviewer.json" = "burscheid"
#"https://ode.map.ffgl.eu/new/data/meshviewer.json" = "odenthal"
#"https://rrh.map.ffgl.eu/new/data/meshviewer.json" = "roesrath"
#"https://lln.map.ffgl.eu/new/data/meshviewer.json" = "leichlingen"

## Greifswald
"https://map.ffhgw.de/data/meshviewer.json" = "greifswald"
"https://yanic.wieckertor.ffhgw.de/data/meshviewer.json" = "greifswald"
"https://unifi.greifswald.freifunk.net/data/meshviewer.json" = "greifswald"

## Gütersloh
"http://hopglass.4830.org/yanic/ffgt/meshviewer.json" = "guetersloh"

## Hannover
"https://harvester.ffh.zone/api/meshviewer.json" = "hannover"

## Hennef (no active yanic - old file)
# "https://map.freifunk-hennef.de/yanic/meshviewer.json" = "hennef"

## Hochstift
"https://map.hochstift.freifunk.net/data/pad-cty/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pad-uml/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/buq/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-nord/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-ost/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-sued/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-west/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/hx-nord/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/hx-sued/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/uml/meshviewer.json" = "hochstift"

## Ingolstad"
"https://map.freifunk-ingolstadt.de/yanic/meshviewer.json" = "ingolstadt"

## Iserlohn (no active feed)
#"https://map.freifunk-iserlohn.de/new/data/meshviewer.json" = "iserlohn"

## Kiel (no yanic/meshviewer.json)
# "https://map.freifunk.in-kiel.de/yanic/meshviewer.json" = "kiel"

## Karlsruhe
"https://api.karlsruhe.freifunk.net/yanic/meshviewer/meshviewer.json" = "karlsruhe"

## Kitzingen
"https://map.freifunk-kitzingen.de/data/meshviewer.json" = "kitzingen"

## Koblenz
"https://status.freifunk-myk.de/data/meshviewer.json" = "mayen-koblenz"

## Koeln
"https://map.kbu.freifunk.net/data/ffeu/meshviewer.json" = "koeln"
"https://map.kbu.freifunk.net/data/ffkbub-V2/meshviewer.json" = "koeln"
"https://map.kbu.freifunk.net/data/ffkbuk/meshviewer.json" = "koeln"
"https://map.kbu.freifunk.net/data/ffkbuu/meshviewer.json" = "koeln"

## Leipzig
"http://karte.leipzig.freifunk.net:8018/meshviewer2/data/meshviewer.json" = "leipzig"

## Leverkusen
"https://map.fflev.de/data/meshviewer.json" = "leverkusen"

## Lippe
"https://karte.freifunk-lippe.de/karte/data/meshviewer.json" = "lippe"

## Lueneburg
"http://gw4.freifunk-lueneburg.de/meshviewer/data/meshviewer.json" = "lueneburg"

## Märkischen Kreis (no active feed)
#"https://map-altena.freifunk-mk.de/new/data/meshviewer.json"  = "altena"
#"https://map-hemer.freifunk-mk.de/new/data/meshviewer.json" = "hemer"
#"https://map-luedenscheid.freifunk-mk.de/new/data/meshviewer.json" = "luedenscheid"
#"https://map-meinerzhagen.freifunk-mk.de/new/data/meshviewer.json" = "meinerzhagen"
#"https://map-neuenrade.freifunk-mk.de/new/data/meshviewer.json" = "neuenrade"

## Mainz, Wiesbaden & Umgebung (MWU)
"https://map.freifunk-mwu.de/data/meshviewer.json" = "mwu"

## Muenchen 
"https://map.ffmuc.net/yanic/meshviewer.json" = "muenchen"

## Müritz / Feldberg
"http://hopglass.4830.org/yanic/muer/meshviewer.json" = "mueritz"
"http://hopglass.4830.org/yanic/tng/meshviewer.json" = "mueritz"

## Niersufer
"https://map.freifunk-niersufer.de/data/meshviewer.json" = "niersufer"

## Nord
"https://mesh.freifunknord.de/data/meshviewer.json" = "nord"
"https://mesh.freifunknord.de/iz/meshviewer.json" = "nord"
"https://mesh.freifunknord.de/ploh/meshviewer.json" = "nord"

## Nordheide
"http://map.freifunk-nordheide.de/data/meshviewer.json" = "nordheide"

## Nordhessen
"https://map.freifunk-nordhessen.de/data/meshviewer.json" = "nordhessen"

## Nordwest
"https://map.ffnw.de/data/meshviewer.json" = "nordwest"

## Neanderfunk (no active feed)
#"https://han.karte.neanderfunk.de/new/data/meshviewer.json" = "haan"
#"https://hlg.karte.neanderfunk.de/new/data/meshviewer.json" = "heiligenhaus"
#"https://hld.karte.neanderfunk.de/new/data/meshviewer.json" = "hilden"
#"https://erk.karte.neanderfunk.de/new/data/meshviewer.json" = "erkrath"
#"https://lgf.karte.neanderfunk.de/new/data/meshviewer.json" = "langenfeld"
#"https://met.karte.neanderfunk.de/new/data/meshviewer.json" = "mettmann"
#"https://mon.karte.neanderfunk.de/new/data/meshviewer.json" = "monheim"
#"https://rat.karte.neanderfunk.de/new/data/meshviewer.json" = "ratingen"
#"https://vel.karte.neanderfunk.de/new/data/meshviewer.json" = "velbert"
#"https://wlf.karte.neanderfunk.de/new/data/meshviewer.json" = "wuelfrath"

## Ostholstein
"https://coco.ffoh.de/meshviewer/data/meshviewer.json" = "ostholstein"

## Regensburg
"https://regensburg.freifunk.net/data/meshviewer.json" = "regensburg"

## Remscheid (looks dead - domain unused)
# "https://map.rs.freifunk.net/data/meshviewer.json" = "remscheid"

## Rhein-Neckar
"https://map.ffrn.de/data/meshviewer.json" = "rhein-neckar"

## Rhein-Sieg
"https://map.freifunk-rhein-sieg.net/data/tdf4/tdf/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/tdf5/inn/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/tdf6/flu/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/siegburg1/domain01/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/siegburg2/domain02/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/siegburg2/domain05/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar1/domain01/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar1/domain03/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar2/domain05/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar3/domain04/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar3/domain07/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/lohmar3/domain11/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/voreifel1/domain15/meshviewer.json" = "rhein-sieg"

## Roenkhausen
"https://map.roenkhausen.de/meshviewer/data/meshviewer.json" = "roenkhausen"

## Rothenburg
"https://netmon.freifunk-rothenburg.de/meshviewer/data/meshviewer.json" = "rothenburg"

## Ruhrgebiet West
"https://map.freifunk.ruhr/data/rgw/meshviewer.json" = "ruhr"

## Stuttgart
"https://map.freifunk-stuttgart.de/data/meshviewer.json" = "stuttgart"

## Suedholstein
"https://map.freifunk-suedholstein.de/data/meshviewer.json" = "suedholstein"

## Suedpfalz
"https://new.freifunk-suedpfalz.de/netzausbau/data/meshviewer.json" = "suedpfalz"

## Trier
"https://maps.tackin.de/data/meshviewer.json" = "trier"

## Troisdorf
"https://map.freifunk-troisdorf.de/data/api/meshviewer.json" = "troisdorf"

## Tuttlingen (invlaid format - non-standard)
# "https://map.freifunk-3laendereck.net/map-data/fftut/meshviewer.json" = "tuttlingen"

## Uelzen (no meshviwer json - looks like an really old yanic)
# "https://map.ffue.eu/data/meshviewer.json" = "uelzen"

## Ulm (invlaid format - non-standard)
# "https://map11.freifunk-ulm.de/data/meshviewer.json" = "ulm"

## Vogtland
"https://mapdata.freifunk-vogtland.net/meshviewer.json" = "vogtland"

## Wels
"http://leto.wels.funkfeuer.at:8080/meshviewer/data/meshviewer.json" = "wels"

## Winterberg
"https://map.freifunk-winterberg.net/data/wtbg/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/sdlh/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/hd/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/mdb/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/doerfer/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/hlb/meshviewer.json" = "winterberg"

## Westpfalz
"https://api.karlsruhe.freifunk.net/yanic/meshviewer/ffwp/meshviewer.json" = "westpfalz"


[yanic_connection]
type          = "udp6"
address       = "local-ext:11001"
