run_every = "5m"

ignore_meshviewer = "6h"
ignore_node = "3d"

status_json = "/var/www/html/collector/status.json"

##
# dataPaths

[dataPaths]
## 3 Laendereck
"https://map.freifunk-3laendereck.net/data/meshviewer.json" = "3laendereck"

## Altdorf
"https://map.tecff.de/yanic/meshviewer.json" = "altdorf"

## Aachen + regio aachen
"https://data.aachen.freifunk.net/new/meshviewer.json" = "aachen"

## Bodensee
"https://meta.ffbsee.net/data/meshviewer.json" = "bodensee"

## Bremen
"https://downloads.bremen.freifunk.net/data/meshviewer.json" = "bremen"

## Darmstadt
"https://meshviewer.darmstadt.freifunk.net/data/meshviewer.json" = "darmstadt"

## Einbeck
"http://vps643489.ovh.net/meshviewer/data/meshviewer.json" = "einbeck"

## Erfurt
"https://map.erfurt.freifunk.net/data/meshviewer.json" = "erfurt"

## Essen
"https://map.freifunk-essen.de/data/meshviewer.json" = "essen"

## Ennepe-Ruhr-Kreis
"https://map.ff-en.de/data/ept/meshviewer.json" = "ennepetal"
"https://map.ff-en.de/data/en/meshviewer.json" = "en-kreis"
"https://map.ff-en.de/data/hat/meshviewer.json" = "hattingen"
"https://map.ff-en.de/data/spr/meshviewer.json" = "sprockhoevel"
"https://map.ff-en.de/data/wtt/meshviewer.json" = "wetter"
"https://map.ff-en.de/data/wit/meshviewer.json" = "witten"

## Eulenfunk (no active ffeds)
#"https://freudenberg.map.eulenfunk.de/new/data/meshviewer.json" = "freudenberg"
#"https://gek.map.eulenfunk.de/new/data/meshviewer.json" = "gelsenkirchen"
#"https://hilchenbach.map.eulenfunk.de/new/data/meshviewer.json" = "hilchenbach"
#"https://mk.map.eulenfunk.de/new/data/meshviewer.json" = "maerkischer-kreis"
#"https://rade.map.eulenfunk.de/new/data/meshviewer.json" = "radevormwald"
#"https://siegen.map.eulenfunk.de/new/data/meshviewer.json" = "siegen"
#"https://wup.map.eulenfunk.de/new/data/meshviewer.json" = "wuppertal"

## Flingern (no active feed)
#"https://karte.ffdus.de/new/data/meshviewer.json" = "flingern"

## Frankenberg
"https://map.freifunk-fkb.de/data/fkb/meshviewer.json" = "frankenberg"
"https://map.freifunk-fkb.de/data/ebl/meshviewer.json" = "frankenberg"
"https://map.freifunk-fkb.de/data/kb/meshviewer.json" = "frankenberg"
"https://map.freifunk-fkb.de/data/bw/meshviewer.json" = "frankenberg"

## Frankfurt
"https://yanic.ffm.freifunk.net/meshviewer.json" = "frankfurt"

## Gera-Greiz
"https://www.freifunk-gera-greiz.de/meshviewer/data/meshviewer.json" ="gera-greiz"

## Gladbach (no active feeds)
#"https://bgl.map.ffgl.eu/new/data/meshviewer.json" = "bergisch-gladbach"
#"https://bcd.map.ffgl.eu/new/data/meshviewer.json" = "burscheid"
#"https://ode.map.ffgl.eu/new/data/meshviewer.json" = "odenthal"
#"https://rrh.map.ffgl.eu/new/data/meshviewer.json" = "roesrath"
#"https://lln.map.ffgl.eu/new/data/meshviewer.json" = "leichlingen"

## Greifswald
"https://map.ffhgw.de/data/meshviewer.json" = "greifswald"
"https://unifi.greifswald.freifunk.net/data/meshviewer.json" = "greifswald"

## Gütersloh
"http://hopglass.4830.org/yanic/ffgt/meshviewer.json" = "guetersloh"

## Hannover
"https://harvester.ffh.zone/meshviewer.json" = "hannover"

## Hennef
"https://map.freifunk-hennef.de/yanic/meshviewer.json" = "hennef"

## Hochstift
"https://map.hochstift.freifunk.net/data/pad-cty/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pad-uml/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/buq/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-nord/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-ost/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-sued/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/pb-west/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/hx-nord/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/hx-sued/meshviewer.json" = "hochstift"
"https://map.hochstift.freifunk.net/data/uml/meshviewer.json" = "hochstift"

## Iserlohn (no active feed)
#"https://map.freifunk-iserlohn.de/new/data/meshviewer.json" = "iserlohn"

## Kiel
"https://map.freifunk.in-kiel.de/yanic/meshviewer.json" = "kiel"

## Karlsruhe
"https://api.karlsruhe.freifunk.net/yanic/meshviewer/meshviewer.json" = "karlsruhe"

## Koeln
"https://map.ffkbu.de/data/meshviewer.json" = "koeln"
"https://map.ffkbu.de/data-man/meshviewer.json" = "koeln"
"https://map.ffkbu.de/data/ffkbub-V2/meshviewer.json" = "koeln"
"https://map.ffkbu.de/data/ffkbub/meshviewer.json" = "koeln"
"https://map.ffkbu.de/data/ffkw/meshviewer.json" = "koeln"

## Koenigswinter
"http://map.freifunk-koenigswinter.de/data/meshviewer.json" = "koenigswinter"

## Leipzig
"http://karte.leipzig.freifunk.net:8018/meshviewer2/data/meshviewer.json" = "leipzig"

## Leverkusen
"https://map.fflev.de/data/meshviewer.json" = "leverkusen"

## Lueneburg
"http://gw4.freifunk-lueneburg.de/meshviewer/data/meshviewer.json" = "lueneburg"

## Märkischen Kreis (no active feed)
#"https://map-altena.freifunk-mk.de/new/data/meshviewer.json"  = "altena"
#"https://map-hemer.freifunk-mk.de/new/data/meshviewer.json" = "hemer"
#"https://map-luedenscheid.freifunk-mk.de/new/data/meshviewer.json" = "luedenscheid"
#"https://map-meinerzhagen.freifunk-mk.de/new/data/meshviewer.json" = "meinerzhagen"
#"https://map-neuenrade.freifunk-mk.de/new/data/meshviewer.json" = "neuenrade"

## Mainz, Wiesbaden & Umgebung (MWU)
"https://map.freifunk-mwu.de/data/meshviewer.json" = "mwu"

## Muenchen 
"https://map.ffmuc.net/yanic/meshviewer.json" = "muenchen"

## Müritz / Feldberg
"http://hopglass.4830.org/yanic/muer/meshviewer.json" ~ "mueritz"
"http://hopglass.4830.org/yanic/tng/meshviewer.json" ~ "mueritz"

## Niersufer
"https://map.freifunk-niersufer.de/data/meshviewer.json" = "niersufer"

## Nord
"https://mesh.freifunknord.de/data/v2/meshviewer.json" = "nord"

## Nordwest
"https://map.ffnw.de/data/meshviewer.json" = "nordwest"

## Neanderfunk (no active feed)
#"https://han.karte.neanderfunk.de/new/data/meshviewer.json" = "haan"
#"https://hlg.karte.neanderfunk.de/new/data/meshviewer.json" = "heiligenhaus"
#"https://hld.karte.neanderfunk.de/new/data/meshviewer.json" = "hilden"
#"https://erk.karte.neanderfunk.de/new/data/meshviewer.json" = "erkrath"
#"https://lgf.karte.neanderfunk.de/new/data/meshviewer.json" = "langenfeld"
#"https://met.karte.neanderfunk.de/new/data/meshviewer.json" = "mettmann"
#"https://mon.karte.neanderfunk.de/new/data/meshviewer.json" = "monheim"
#"https://rat.karte.neanderfunk.de/new/data/meshviewer.json" = "ratingen"
#"https://vel.karte.neanderfunk.de/new/data/meshviewer.json" = "velbert"
#"https://wlf.karte.neanderfunk.de/new/data/meshviewer.json" = "wuelfrath"

## Ostholstein
"https://coco.ffoh.de/meshviewer/data/meshviewer.json" = "ostholstein"

## Trier
"http://maps.tackin.de/data/meshviewer.json" = "trier"

## Regensburg
"https://regensburg.freifunk.net/data/meshviewer.json" = "regensburg"

## Rhein-Neckar
"https://map.ffrn.de/data/meshviewer.json" = "rhein-neckar"

## Rhein-Sieg
"https://map.freifunk-rhein-sieg.net/data/tdf4/tdf/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/tdf5/inn/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/tdf6/flu/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw01/domain07/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw02/domain01/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw02/domain03/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw03/domain04/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw03/domain05/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw04/domain11/meshviewer.json" = "rhein-sieg"
"https://map.freifunk-rhein-sieg.net/data/fgw04/domain14/meshviewer.json" = "rhein-sieg"

## Roenkhausen
"https://map.roenkhausen.de/meshviewer/data/meshviewer.json" = "roenkhausen"

## Ruhrgebiet West
"https://map.freifunk.ruhr/data/rgw/meshviewer.json" = "ruhr"

## Suedholstein
"https://map.freifunk-suedholstein.de/data/meshviewer.json" = "suedholstein"

## Troisdorf
"https://map.freifunk-troisdorf.de/data/tdf4/meshviewer.json" = "troisdorf"

## Uelzen (no active feed)
# "https://map.ffue.eu/data/meshviewer.json" = "uelzen"

## Ulm
"https://map10.freifunk-ulm.de/data/meshviewer.json" = "ulm"

## Vogtland
"https://mapdata.freifunk-vogtland.net/meshviewer.json" = "vogtland"

## Wels
"http://leto.wels.funkfeuer.at:8080/meshviewer/data/meshviewer.json"  = "wels"

## Winterberg
"https://map.freifunk-winterberg.net/data/wtbg/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/sdlh/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/hd/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/mdb/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/doerfer/meshviewer.json" = "winterberg"
"https://map.freifunk-winterberg.net/data/hlb/meshviewer.json" = "winterberg"

## Westpfalz (merged with karlsruhe)
# "https://map.freifunk-westpfalz.de/data/meshviewer.json" = "westpfalz"


[yanic_connection]
type          = "udp6"
address       = "local-ext:11001"
