run_every = "5m"

output = "/srv/http/domain/web.fireorbit.de/meshviewer/data/meshviewer.json"
ignore_meshviewer = "6h"
ignore_node = "3d"

##
# dataPaths

dataPaths = [
	## Aachen + regio aachen
	"https://data.aachen.freifunk.net/new/meshviewer.json",

	## Bremen
	"https://downloads.bremen.freifunk.net/data/meshviewer.json",

	## Darmstadt
	"https://meshviewer.darmstadt.freifunk.net/data/meshviewer.json",

	## Einbeck
	"http://vpn1.freifunk-einbeck.de/meshviewer/data/meshviewer.json",

	## Ennepe-Ruhr-Kreis
	"https://map.ff-en.de/data/ept/meshviewer.json", # Ennepetal
	"https://map.ff-en.de/data/en/meshviewer.json",  # EN-Kreis
	"https://map.ff-en.de/data/hat/meshviewer.json", # Hattingen
	"https://map.ff-en.de/data/spr/meshviewer.json", # Sprockhoevel
	"https://map.ff-en.de/data/wtt/meshviewer.json", # Wetter
	"https://map.ff-en.de/data/wit/meshviewer.json", # Witten

	## Eulenfunk
	"https://freudenberg.map.eulenfunk.de/new/data/meshviewer.json", # Freudenberg
	"https://gek.map.eulenfunk.de/new/data/meshviewer.json", # Gelsenkirchen
	"https://hilchenbach.map.eulenfunk.de/new/data/meshviewer.json", # Hilchenbach
	"https://mk.map.eulenfunk.de/new/data/meshviewer.json", # Märkischer Kreis
	"https://rade.map.eulenfunk.de/new/data/meshviewer.json", # Radevormwald
	"https://siegen.map.eulenfunk.de/new/data/meshviewer.json", # Siegen
	"https://wup.map.eulenfunk.de/new/data/meshviewer.json", # Wuppertal

	## Flingern
	"https://karte.ffdus.de/new/data/meshviewer.json",

	## Frankfurt
	"https://yanic.ffm.freifunk.net/legacy/meshviewer.json",

	## Gera-Greiz
	"https://www.freifunk-gera-greiz.de/meshviewer/data/meshviewer.json",

	## Gladbach
	"https://bgl.map.ffgl.eu/new/data/meshviewer.json", # Bergisch Gladbach
	"https://bcd.map.ffgl.eu/new/data/meshviewer.json", # Burscheid
	"https://ode.map.ffgl.eu/new/data/meshviewer.json", # Odenthal
	"https://rrh.map.ffgl.eu/new/data/meshviewer.json", # Rösrath
	"https://lln.map.ffgl.eu/new/data/meshviewer.json", # Leichlingen

	## Iserlohn
	"https://map.freifunk-iserlohn.de/new/data/meshviewer.json",

	## Kiel
	"https://map.freifunk.in-kiel.de/yanic/meshviewer.json",

	## Märkischen Kreis
	"https://map-altena.freifunk-mk.de/new/data/meshviewer.json", # Altena
	"https://map-hemer.freifunk-mk.de/new/data/meshviewer.json", # Hemer
	"https://map-luedenscheid.freifunk-mk.de/new/data/meshviewer.json", 	# Lüdenscheid
	"https://map-meinerzhagen.freifunk-mk.de/new/data/meshviewer.json", 	# Meinerzhagen
	"https://map-neuenrade.freifunk-mk.de/new/data/meshviewer.json", 	# Neuenrade

	## Mainz, Wiesbaden & Umgebung (MWU)
	"https://map.freifunk-mwu.de/data/meshviewer.json",

	## Neanderfunk
	"https://han.karte.neanderfunk.de/new/data/meshviewer.json", # Haan
	"https://hlg.karte.neanderfunk.de/new/data/meshviewer.json", # Heiligenhaus
	"https://hld.karte.neanderfunk.de/new/data/meshviewer.json", # Hilden
	"https://erk.karte.neanderfunk.de/new/data/meshviewer.json", # Erkrath
	"https://lgf.karte.neanderfunk.de/new/data/meshviewer.json", # Langenfeld
	"https://met.karte.neanderfunk.de/new/data/meshviewer.json", # Mettmann
	"https://mon.karte.neanderfunk.de/new/data/meshviewer.json", # Monheim
	"https://rat.karte.neanderfunk.de/new/data/meshviewer.json", # Ratingen
	"https://vel.karte.neanderfunk.de/new/data/meshviewer.json", # Velbert
	"https://wlf.karte.neanderfunk.de/new/data/meshviewer.json", # Wülfrath

	## Trier
	"http://maps.tackin.de/data/meshviewer.json",

	## Regensburg
	"https://regensburg.freifunk.net/data/meshviewer.json",

	## Westpfalz
	"https://map.freifunk-westpfalz.de/data/meshviewer.json",

]

[database]
delete_after    = "1d"
delete_interval = "1h"

[[database.connection.influxdb]]
enable          = false
address         = "http://localhost:8086"
database        = "freifunk_multi"
username        = "freifunk_multi"
password        = "not given"

